### ISSUE TITLE
не работает калбек

### ISSUE THREAD

**Issue by limprog** [limprog/keper#5]
не работает в файле с main.py в папке telebot в строчках 607-612 и объявление кнопки 42

**Comment by s70c3** [comment]
```python

@dp.callback_query_handler(lambda c: c.data == 'akk', state="*")
async def change(message: types.Message, callback_query: types.CallbackQuery):
    print("test")
    await bot.answer_callback_query(callback_query.id)

    await bot.send_message(callback_query.from_user.id, 'Нажата первая кнопка!')

``` 

локализована проблема

**Comment by s70c3** [comment]
Опишите, пожалуйста, ожидаемое поведение и фактическое

**Comment by limprog** [comment]
при нажатие кнопки информация о аккаунте должно печататься тест и отправляться   Нажата первая кнопка!, но судя по всему оно даже в функцию не входит

**Comment by s70c3** [comment]
Необходимо убрать параметр message в функции change для решения этой проблемы.
