### ISSUE TITLE
Отсутствует сообщение об ошибке при вводе не существующего логина и пароля

### ISSUE THREAD

**Issue by s70c3** [limprog/keper#7]
Шаги для повторения:
1. Выбрать команду /auth
2. Ввести логин
3. Ввести пароль

Ожидаемое поведение:
сообщение об ошибке

Фактическое поведение:
отсутствие ответа

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/16955799/228966727-9f24cf10-870e-4910-92c8-3cf32a8e84ce.png">

**Comment by limprog** [comment]
![image](https://user-images.githubusercontent.com/84340228/229589567-0df13234-4f8c-46f6-8516-22e4812b06e4.png)
![image](https://user-images.githubusercontent.com/84340228/229590445-adb57fbb-cbb0-4e68-b150-85c93943bd69.png)
на последнем комите ошибка исправлена
