### ISSUE TITLE
Нестабильное поведение при выполнении аутентификации перед регистрацией

### ISSUE THREAD

**Issue by s70c3** [limprog/keper#8]
Шаги для повторения:
1. Попробовать провести аутентификацию как в #7 .
2.  Выбрать команду /reg

Ожидаемое поведение:
запрос логина и пароля

Фактическое поведение:
аутентификация с использованием логина и пароля для #7 .

Возможная причина: в состоянии уже заполнены логин и пароль, считает эту часть выполненной и создаёт аккаунт.

**Comment by limprog** [comment]
вывод убрать возможность начинать регистрацию при auth. Будет исправлено с появлением кнопок

**Comment by limprog** [comment]
после полного отключения команд ошибка будет исправлена, однако фактически оно уже исправлена 
@s70c3

**Comment by s70c3** [comment]
@limprog открыто, пока не будет исправлено с обновлением :)
